version: '3'
services:
  api:
    image: node:14.15.0
    ports:
      - '${API_PORT:-3001}:3000'
    volumes:
      - advanced-sns-api-sync:/usr/local/advanced-sns-api:nocopy
    working_dir: /usr/local/advanced-sns-api
    tty: true
    entrypoint: "/bin/sh -c 'yarn install; yarn typeorm migration:run; yarn dev'"
    depends_on:
      - db

  db:
    image: mysql:8.0.22
    platform: linux/x86_64
    ports:
      - '${DB_PORT:-3308}:3306'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: advanced_sns
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - advanced-sns-mysql-data:/var/lib/mysql
      - ./docker/db:/docker-entrypoint-initdb.d

volumes:
  advanced-sns-mysql-data:
  advanced-sns-api-sync:
    external: true
